version: '3.8'

services:
  app:
    build: .
    container_name: my_app
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: my_db
    environment:
      POSTGRES_USER: Etapa1
      POSTGRES_PASSWORD: etapa1
      POSTGRES_DB: Etapa1DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
